### ISSUE TITLE
accuracy is very low

### ISSUE THREAD

**Issue by jumpapex** [PatWie/tfGo#2]
Dear Patrick,

Thank for you great work!

I just following the instructions, but the accuracy is no more than 0.1 after 60+ epochs training on GoGoD sgf files.

Because PrefetchData and PrefetchDataZMQ does not work on my machine(windows 10, python 3.6, 64bit), I just comment them out. I have only one GPU.

def get_data(lmdb, isTrain=False):
    df = LMDBDataPoint(lmdb, shuffle=isTrain)
    # df = PrefetchData(df, 5000, 1)
    df = GameDecoder(df, random_move=True)
    df = DihedralGroup(df)
    # if isTrain:
    #      df = PrefetchDataZMQ(df, min(20, multiprocessing.cpu_count()))
    df = BatchData(df, BATCH_SIZE, remainder=not isTrain)
    return df

I just wonder whether the comment make it not work, or others. 

Regards!

Jumapex

**Comment by PatWie** [comment]
`PrefetchData and PrefetchDataZMQ` are just a way to accelerate the training. I am not aware of any side effects on windows machines. But these changes should not affect the performance. I won't provide any updates, this work is already out-date and currently not part of my research interest.
